'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace ServiceReference2
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="urn:sap-com:document:sap:rfc:functions", ConfigurationName:="ServiceReference2.ZWS_SPU_MATERIAL_LIST_SRV")>  _
    Public Interface ZWS_SPU_MATERIAL_LIST_SRV
        
        'CODEGEN: Generating message contract since the operation ZFM_SPU_MATERIALS is neither RPC nor document wrapped.
        <System.ServiceModel.OperationContractAttribute(Action:="urn:sap-com:document:sap:rfc:functions:ZWS_SPU_MATERIAL_LIST_SRV:ZFM_SPU_MATERIAL"& _ 
            "SRequest", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function ZFM_SPU_MATERIALS(ByVal request As ServiceReference2.ZFM_SPU_MATERIALSRequest) As ServiceReference2.ZFM_SPU_MATERIALSResponse1
        
        <System.ServiceModel.OperationContractAttribute(Action:="urn:sap-com:document:sap:rfc:functions:ZWS_SPU_MATERIAL_LIST_SRV:ZFM_SPU_MATERIAL"& _ 
            "SRequest", ReplyAction:="*")>  _
        Function ZFM_SPU_MATERIALSAsync(ByVal request As ServiceReference2.ZFM_SPU_MATERIALSRequest) As System.Threading.Tasks.Task(Of ServiceReference2.ZFM_SPU_MATERIALSResponse1)
    End Interface
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="urn:sap-com:document:sap:rfc:functions")>  _
    Partial Public Class ZFM_SPU_MATERIALS
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:sap-com:document:sap:rfc:functions")>  _
    Partial Public Class ZSPU_MATERIAL
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private mATNRField As String
        
        Private mAT_CATField As String
        
        Private mTARTField As String
        
        Private mAKTGField As String
        
        Private mEINSField As String
        
        Private mATKLField As String
        
        Private sTEUCField As String
        
        Private tAX_TYPEField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property MATNR() As String
            Get
                Return Me.mATNRField
            End Get
            Set
                Me.mATNRField = value
                Me.RaisePropertyChanged("MATNR")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property MAT_CAT() As String
            Get
                Return Me.mAT_CATField
            End Get
            Set
                Me.mAT_CATField = value
                Me.RaisePropertyChanged("MAT_CAT")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property MTART() As String
            Get
                Return Me.mTARTField
            End Get
            Set
                Me.mTARTField = value
                Me.RaisePropertyChanged("MTART")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=3)>  _
        Public Property MAKTG() As String
            Get
                Return Me.mAKTGField
            End Get
            Set
                Me.mAKTGField = value
                Me.RaisePropertyChanged("MAKTG")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=4)>  _
        Public Property MEINS() As String
            Get
                Return Me.mEINSField
            End Get
            Set
                Me.mEINSField = value
                Me.RaisePropertyChanged("MEINS")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=5)>  _
        Public Property MATKL() As String
            Get
                Return Me.mATKLField
            End Get
            Set
                Me.mATKLField = value
                Me.RaisePropertyChanged("MATKL")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=6)>  _
        Public Property STEUC() As String
            Get
                Return Me.sTEUCField
            End Get
            Set
                Me.sTEUCField = value
                Me.RaisePropertyChanged("STEUC")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=7)>  _
        Public Property TAX_TYPE() As String
            Get
                Return Me.tAX_TYPEField
            End Get
            Set
                Me.tAX_TYPEField = value
                Me.RaisePropertyChanged("TAX_TYPE")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="urn:sap-com:document:sap:rfc:functions")>  _
    Partial Public Class ZFM_SPU_MATERIALSResponse
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private eT_MATERIALSField() As ZSPU_MATERIAL
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0),  _
         System.Xml.Serialization.XmlArrayItemAttribute("item", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property ET_MATERIALS() As ZSPU_MATERIAL()
            Get
                Return Me.eT_MATERIALSField
            End Get
            Set
                Me.eT_MATERIALSField = value
                Me.RaisePropertyChanged("ET_MATERIALS")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ZFM_SPU_MATERIALSRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="urn:sap-com:document:sap:rfc:functions", Order:=0)>  _
        Public ZFM_SPU_MATERIALS As ServiceReference2.ZFM_SPU_MATERIALS
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ZFM_SPU_MATERIALS As ServiceReference2.ZFM_SPU_MATERIALS)
            MyBase.New
            Me.ZFM_SPU_MATERIALS = ZFM_SPU_MATERIALS
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ZFM_SPU_MATERIALSResponse1
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="urn:sap-com:document:sap:rfc:functions", Order:=0)>  _
        Public ZFM_SPU_MATERIALSResponse As ServiceReference2.ZFM_SPU_MATERIALSResponse
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ZFM_SPU_MATERIALSResponse As ServiceReference2.ZFM_SPU_MATERIALSResponse)
            MyBase.New
            Me.ZFM_SPU_MATERIALSResponse = ZFM_SPU_MATERIALSResponse
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ZWS_SPU_MATERIAL_LIST_SRVChannel
        Inherits ServiceReference2.ZWS_SPU_MATERIAL_LIST_SRV, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ZWS_SPU_MATERIAL_LIST_SRVClient
        Inherits System.ServiceModel.ClientBase(Of ServiceReference2.ZWS_SPU_MATERIAL_LIST_SRV)
        Implements ServiceReference2.ZWS_SPU_MATERIAL_LIST_SRV
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference2_ZWS_SPU_MATERIAL_LIST_SRV_ZFM_SPU_MATERIALS(ByVal request As ServiceReference2.ZFM_SPU_MATERIALSRequest) As ServiceReference2.ZFM_SPU_MATERIALSResponse1 Implements ServiceReference2.ZWS_SPU_MATERIAL_LIST_SRV.ZFM_SPU_MATERIALS
            Return MyBase.Channel.ZFM_SPU_MATERIALS(request)
        End Function
        
        Public Function ZFM_SPU_MATERIALS(ByVal ZFM_SPU_MATERIALS1 As ServiceReference2.ZFM_SPU_MATERIALS) As ServiceReference2.ZFM_SPU_MATERIALSResponse
            Dim inValue As ServiceReference2.ZFM_SPU_MATERIALSRequest = New ServiceReference2.ZFM_SPU_MATERIALSRequest()
            inValue.ZFM_SPU_MATERIALS = ZFM_SPU_MATERIALS1
            Dim retVal As ServiceReference2.ZFM_SPU_MATERIALSResponse1 = CType(Me,ServiceReference2.ZWS_SPU_MATERIAL_LIST_SRV).ZFM_SPU_MATERIALS(inValue)
            Return retVal.ZFM_SPU_MATERIALSResponse
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference2_ZWS_SPU_MATERIAL_LIST_SRV_ZFM_SPU_MATERIALSAsync(ByVal request As ServiceReference2.ZFM_SPU_MATERIALSRequest) As System.Threading.Tasks.Task(Of ServiceReference2.ZFM_SPU_MATERIALSResponse1) Implements ServiceReference2.ZWS_SPU_MATERIAL_LIST_SRV.ZFM_SPU_MATERIALSAsync
            Return MyBase.Channel.ZFM_SPU_MATERIALSAsync(request)
        End Function
        
        Public Function ZFM_SPU_MATERIALSAsync(ByVal ZFM_SPU_MATERIALS As ServiceReference2.ZFM_SPU_MATERIALS) As System.Threading.Tasks.Task(Of ServiceReference2.ZFM_SPU_MATERIALSResponse1)
            Dim inValue As ServiceReference2.ZFM_SPU_MATERIALSRequest = New ServiceReference2.ZFM_SPU_MATERIALSRequest()
            inValue.ZFM_SPU_MATERIALS = ZFM_SPU_MATERIALS
            Return CType(Me,ServiceReference2.ZWS_SPU_MATERIAL_LIST_SRV).ZFM_SPU_MATERIALSAsync(inValue)
        End Function
    End Class
End Namespace
