'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace ServiceReference3
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="urn:sap-com:document:sap:rfc:functions", ConfigurationName:="ServiceReference3.ZWS_SPU_VENDOR_LIST_SRV")>  _
    Public Interface ZWS_SPU_VENDOR_LIST_SRV
        
        'CODEGEN: Generating message contract since the operation ZFM_SPU_VENDORS is neither RPC nor document wrapped.
        <System.ServiceModel.OperationContractAttribute(Action:="urn:sap-com:document:sap:rfc:functions:ZWS_SPU_VENDOR_LIST_SRV:ZFM_SPU_VENDORSReq"& _ 
            "uest", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function ZFM_SPU_VENDORS(ByVal request As ServiceReference3.ZFM_SPU_VENDORSRequest) As ServiceReference3.ZFM_SPU_VENDORSResponse1
        
        <System.ServiceModel.OperationContractAttribute(Action:="urn:sap-com:document:sap:rfc:functions:ZWS_SPU_VENDOR_LIST_SRV:ZFM_SPU_VENDORSReq"& _ 
            "uest", ReplyAction:="*")>  _
        Function ZFM_SPU_VENDORSAsync(ByVal request As ServiceReference3.ZFM_SPU_VENDORSRequest) As System.Threading.Tasks.Task(Of ServiceReference3.ZFM_SPU_VENDORSResponse1)
    End Interface
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="urn:sap-com:document:sap:rfc:functions")>  _
    Partial Public Class ZFM_SPU_VENDORS
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:sap-com:document:sap:rfc:functions")>  _
    Partial Public Class ZSPU_VENDOR
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private lIFNRField As String
        
        Private nAME1Field As String
        
        Private sTRASField As String
        
        Private vKBURField As String
        
        Private sTCD3Field As String
        
        Private pANField As String
        
        Private tELF1Field As String
        
        Private sMTP_ADDRField As String
        
        Private pSTLZField As String
        
        Private vEN_CLASSField As String
        
        Private eRDATField As String
        
        Private rEGIOField As String
        
        Private mCOD3Field As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property LIFNR() As String
            Get
                Return Me.lIFNRField
            End Get
            Set
                Me.lIFNRField = value
                Me.RaisePropertyChanged("LIFNR")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property NAME1() As String
            Get
                Return Me.nAME1Field
            End Get
            Set
                Me.nAME1Field = value
                Me.RaisePropertyChanged("NAME1")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property STRAS() As String
            Get
                Return Me.sTRASField
            End Get
            Set
                Me.sTRASField = value
                Me.RaisePropertyChanged("STRAS")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=3)>  _
        Public Property VKBUR() As String
            Get
                Return Me.vKBURField
            End Get
            Set
                Me.vKBURField = value
                Me.RaisePropertyChanged("VKBUR")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=4)>  _
        Public Property STCD3() As String
            Get
                Return Me.sTCD3Field
            End Get
            Set
                Me.sTCD3Field = value
                Me.RaisePropertyChanged("STCD3")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=5)>  _
        Public Property PAN() As String
            Get
                Return Me.pANField
            End Get
            Set
                Me.pANField = value
                Me.RaisePropertyChanged("PAN")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=6)>  _
        Public Property TELF1() As String
            Get
                Return Me.tELF1Field
            End Get
            Set
                Me.tELF1Field = value
                Me.RaisePropertyChanged("TELF1")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=7)>  _
        Public Property SMTP_ADDR() As String
            Get
                Return Me.sMTP_ADDRField
            End Get
            Set
                Me.sMTP_ADDRField = value
                Me.RaisePropertyChanged("SMTP_ADDR")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=8)>  _
        Public Property PSTLZ() As String
            Get
                Return Me.pSTLZField
            End Get
            Set
                Me.pSTLZField = value
                Me.RaisePropertyChanged("PSTLZ")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=9)>  _
        Public Property VEN_CLASS() As String
            Get
                Return Me.vEN_CLASSField
            End Get
            Set
                Me.vEN_CLASSField = value
                Me.RaisePropertyChanged("VEN_CLASS")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=10)>  _
        Public Property ERDAT() As String
            Get
                Return Me.eRDATField
            End Get
            Set
                Me.eRDATField = value
                Me.RaisePropertyChanged("ERDAT")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=11)>  _
        Public Property REGIO() As String
            Get
                Return Me.rEGIOField
            End Get
            Set
                Me.rEGIOField = value
                Me.RaisePropertyChanged("REGIO")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=12)>  _
        Public Property MCOD3() As String
            Get
                Return Me.mCOD3Field
            End Get
            Set
                Me.mCOD3Field = value
                Me.RaisePropertyChanged("MCOD3")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="urn:sap-com:document:sap:rfc:functions")>  _
    Partial Public Class ZFM_SPU_VENDORSResponse
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private eT_VENDORSField() As ZSPU_VENDOR
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0),  _
         System.Xml.Serialization.XmlArrayItemAttribute("item", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property ET_VENDORS() As ZSPU_VENDOR()
            Get
                Return Me.eT_VENDORSField
            End Get
            Set
                Me.eT_VENDORSField = value
                Me.RaisePropertyChanged("ET_VENDORS")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ZFM_SPU_VENDORSRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="urn:sap-com:document:sap:rfc:functions", Order:=0)>  _
        Public ZFM_SPU_VENDORS As ServiceReference3.ZFM_SPU_VENDORS
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ZFM_SPU_VENDORS As ServiceReference3.ZFM_SPU_VENDORS)
            MyBase.New
            Me.ZFM_SPU_VENDORS = ZFM_SPU_VENDORS
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ZFM_SPU_VENDORSResponse1
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="urn:sap-com:document:sap:rfc:functions", Order:=0)>  _
        Public ZFM_SPU_VENDORSResponse As ServiceReference3.ZFM_SPU_VENDORSResponse
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ZFM_SPU_VENDORSResponse As ServiceReference3.ZFM_SPU_VENDORSResponse)
            MyBase.New
            Me.ZFM_SPU_VENDORSResponse = ZFM_SPU_VENDORSResponse
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ZWS_SPU_VENDOR_LIST_SRVChannel
        Inherits ServiceReference3.ZWS_SPU_VENDOR_LIST_SRV, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ZWS_SPU_VENDOR_LIST_SRVClient
        Inherits System.ServiceModel.ClientBase(Of ServiceReference3.ZWS_SPU_VENDOR_LIST_SRV)
        Implements ServiceReference3.ZWS_SPU_VENDOR_LIST_SRV
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference3_ZWS_SPU_VENDOR_LIST_SRV_ZFM_SPU_VENDORS(ByVal request As ServiceReference3.ZFM_SPU_VENDORSRequest) As ServiceReference3.ZFM_SPU_VENDORSResponse1 Implements ServiceReference3.ZWS_SPU_VENDOR_LIST_SRV.ZFM_SPU_VENDORS
            Return MyBase.Channel.ZFM_SPU_VENDORS(request)
        End Function
        
        Public Function ZFM_SPU_VENDORS(ByVal ZFM_SPU_VENDORS1 As ServiceReference3.ZFM_SPU_VENDORS) As ServiceReference3.ZFM_SPU_VENDORSResponse
            Dim inValue As ServiceReference3.ZFM_SPU_VENDORSRequest = New ServiceReference3.ZFM_SPU_VENDORSRequest()
            inValue.ZFM_SPU_VENDORS = ZFM_SPU_VENDORS1
            Dim retVal As ServiceReference3.ZFM_SPU_VENDORSResponse1 = CType(Me,ServiceReference3.ZWS_SPU_VENDOR_LIST_SRV).ZFM_SPU_VENDORS(inValue)
            Return retVal.ZFM_SPU_VENDORSResponse
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference3_ZWS_SPU_VENDOR_LIST_SRV_ZFM_SPU_VENDORSAsync(ByVal request As ServiceReference3.ZFM_SPU_VENDORSRequest) As System.Threading.Tasks.Task(Of ServiceReference3.ZFM_SPU_VENDORSResponse1) Implements ServiceReference3.ZWS_SPU_VENDOR_LIST_SRV.ZFM_SPU_VENDORSAsync
            Return MyBase.Channel.ZFM_SPU_VENDORSAsync(request)
        End Function
        
        Public Function ZFM_SPU_VENDORSAsync(ByVal ZFM_SPU_VENDORS As ServiceReference3.ZFM_SPU_VENDORS) As System.Threading.Tasks.Task(Of ServiceReference3.ZFM_SPU_VENDORSResponse1)
            Dim inValue As ServiceReference3.ZFM_SPU_VENDORSRequest = New ServiceReference3.ZFM_SPU_VENDORSRequest()
            inValue.ZFM_SPU_VENDORS = ZFM_SPU_VENDORS
            Return CType(Me,ServiceReference3.ZWS_SPU_VENDOR_LIST_SRV).ZFM_SPU_VENDORSAsync(inValue)
        End Function
    End Class
End Namespace
